config/routes.rb
FirmaExpressR::Application.routes.draw do
  devise_for :users#, controllers: { registrations:'devise/custom/registrations' }
  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  root 'home#homepage'
  get "home" => "documents#new", as: 'user_root' #"new_document"
  get "show" => "documents#show", :as => "show_document"
  get "documents/new"
  get "sessions/new"
  get "users/new"
  get "users/rut", to: "users#rut"
  get "users/invite", to: "users#invite", as: "invite"
  get "/contact", to: "home#contact", as: "contact_form"
  post "users/contact", to: "users#contact", as: "contact"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "/register" => "users#new", :as => "sign_up"
  get "documents/sign/:id", to: "documents#sign"
  get "documents/destroy/:id", to: "documents#destroy"
  get "participants/:user_id/destroy/:document_id", to: "participants#destroy"
  get "documents/list", to: "documents#list"
  get "check_document/:id", to: "documents#check"
  get "/profile", to: "users#profile", as:"profile"
  get "users/update_profile", to: "users#update_profile", as:"update_profile"
  get "users/complete_invitee_profile", to: "users#complete_invitee_profile"
  post "users/complete_invitee_profile", to: "users#complete_invitee_profile"
  post "users/sign_image", to: "users#sign_image"
  default_url_options :host => "Firmaexpress.dev"
  resources :sessions
  resources :documents
  resources :users
  resources :subscriptions
  get 'paypal/checkout', to: 'subscriptions#paypal_checkout'
  get "/about_us", to: "home#aboutus"
  get "/plans", to: "home#plans"
  get "/benefits", to: "home#benefits"
  get "/terms", to: "home#terms"
  get "/get_plan/:plan_id", to: "home#get_plan"
  post "/get_plan_post", to: "home#get_plan_post"
  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    resources :users, only: [:index, :show] do
      resources :documents, only: [:index, :show] do
        resources :signs, only: [:index, :create]
      end
    end
  end

end

app/models/user.rb
class IdNumberValidator < ActiveModel::Validator
  def validate(record)
    rut, dv = record.id_number.split('-')
	rut = rut.delete "."
	rut_reverse = rut.reverse
	multiplier = 2
	real_dv = 0
	for digit in rut_reverse.each_char
		if multiplier > 7
			multiplier = 2
		end
		real_dv += digit.to_i * multiplier
		multiplier += 1
	end
	real_dv = 11 - real_dv % 11
	if real_dv == 10
		real_dv = 'k'
	end
	if real_dv == 11
		real_dv = 0
	end
	if real_dv.to_s != dv
		record.errors[:base] << "RUT inválido"
	end
  end
end
=begin
class IdDocumentSerialValidator < ActiveModel::Validator
	def validate(record)
		OpenSSL::SSL.const_set(:VERIFY_PEER, OpenSSL::SSL::VERIFY_NONE)
		page = Nokogiri::HTML(open("https://portal.sidiv.registrocivil.cl/usuarios-portal/pages/DocumentRequestStatus.xhtml?RUN=#{record.id_number}&type=CEDULA&serial=#{record.id_document_serial}"))
		OpenSSL::SSL.const_set(:VERIFY_PEER, OpenSSL::SSL::VERIFY_PEER)
		unless page.css('.setWidthOfSecondColumn').text == 'Vigente'
			#record.errors[:base] << "Cedula inválida, param: #{record.id_document_serial}, result: #{page.css('.setWidthOfSecondColumn').text}"
			record.errors[:base] << 'Cedula inválida'
		end
	end
end

=end

class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable
	include ActiveModel::Validations
	has_many :participants
	has_many :documents, through: :participants
	has_many :roles, through: :participants
	belongs_to :subscriber
	has_many :invite_codes
	belongs_to :user_type

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "uploads/user.jpg"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	has_attached_file :sign_image, default_url: "uploads/sin-firma.jpg"
	validates_attachment_content_type :sign_image, content_type: /\Aimage\/.*\Z/

	#attr_accessor :password, :password_confirmation, :current_password
	attr_accessor :invite_code
	#attr_accessor :id_document_serial
	attr_accessor :terms
	attr_accessor :plan_id
	attr_accessor :paypal_customer_token
	attr_accessor :paypal_payment_token
	before_validation :set_user_id

	validates :password,
				presence: true,
				on: :create,
				unless: Proc.new { |a| a.user_type_id == 4 }

	validates :email,
				presence: true,
				uniqueness: true,
				format: { with: /[-0-9a-zA-Z.+_]+@[-0-9a-zA-Z.+_]+\.[a-zA-Z]{2,4}/, message: "Formato de correo no es válido" }
	validates :first_name,
				presence: true,
				unless: Proc.new { |a| a.user_type_id == 4 }
	validates :last_name,
				presence: true,
				unless: Proc.new { |a| a.user_type_id == 4 }
	#validates :avatar,
	#			presence: true
	validates :id_number,
				presence: true,
				uniqueness: true,
				unless: Proc.new { |a| a.user_type_id == 4 }
	validates_with IdNumberValidator,
				#unless: Proc.new { |a| a.user_type_id == 4 }
	#validates_with IdDocumentSerialValidator,
				unless: Proc.new { |a| a.user_type_id == 4 }
	validates_acceptance_of :terms

=begin
	def generate_codes
		unless self.invite_codes
			3.times do
				self.invite_codes << InviteCode.create()
			end
		end
	end
=end

	def set_user_id
		self.user_type_id = 2 if self.user_type_id.blank?
		unless self.user_type_id == 4
			rut, dv = id_number.split('-')
			rut = rut.delete "."
			#sii_page = Nokogiri::HTML(open("https://zeus.sii.cl/cvc_cgi/stc/getstc?RUT=#{rut}&DV=#{dv}&PRG=STC&OPC=NOR"))
			begin
				#full_name = sii_page.css('html body center')[1].css('table')[0].css('tr')[0].css('td')[1].css('font').text.strip.titleize
				full_name = JSON.parse(open("https://siichile.herokuapp.com/consulta?rut=#{rut}-#{dv}").read())['razon_social']
				self.first_name = full_name.match(/^([^ ]*\ [^ ]*)\ (.*)$/)[1].titleize
				self.last_name = full_name.match(/^([^ ]*\ [^ ]*)\ (.*)$/)[2].titleize
			rescue Exception => e
				self.first_name = ''
				self.last_name = ''
			end
		end
		if plan_id.present?
			subscribe(plan_id)
		else
			subscribe(1)
		end
	end

	def subscribe(plan_id)
		self.subscriber = Subscriber.create if self.subscriber.nil?
		self.subscriber.plans << Plan.find(plan_id) if plan_id == 1
		if plan_id != 1 and paypal_customer_token.present?
			subscription = Subscription.new(
				paypal_customer_token: paypal_customer_token, 
				paypal_payment_token: paypal_payment_token)
			subscription.plan = Plan.find(plan_id)
			subscription.save_with_payment
			self.subscriber.subscriptions << subscription
		end
	end

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
	has_many :users
end

app/controllers/api/users_controller.rb
module API
	class UsersController < APIController
		def index
			users = User.all
			respond_to do |format|
				format.json { render json: users, status: :ok } #200
			end
		end

		def show
			user = User.find(params[:id])
			respond_to do |format|
				format.json { render json: user, status: :ok } #200
			end
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except: [:complete_invitee_profile, :rut]
	before_action :invitations, :invitations_left
	#before_action :check_auth, only: [:profile, :invite]
	def new
		@user = User.new
		user_id = params[:u]
		code = params[:c]
		if user_id
			@user = User.find(user_id)
		end
		if code
			@user.invite_code = code
		end
	end

	def show
		sign_out :user
		redirect_to user_root_url
	end

	def sign_image
		current_user.update(sign_image: params[:sign_image])
		redirect_to user_root_url
	end

	def rut
		rut = params[:rut].split('-')[0]
		dv = params[:rut].split('-')[1].upcase
		serial = params[:serial].upcase
		name = ''
		rut_sii = ''
		serial_valid = true
		code = 0
		OpenSSL::SSL.const_set(:VERIFY_PEER, OpenSSL::SSL::VERIFY_NONE)
		sii_page = Nokogiri::HTML(open("https://zeus.sii.cl/cvc_cgi/stc/getstc?RUT=#{rut}&DV=#{dv}&PRG=STC&OPC=NOR"))
		begin
			rut_sii = name = sii_page.css('html body center')[1].css('table')[0].css('tr')[1].css('td')[1].css('font').text
			code = 200
		rescue Exception => e
			code = 404
		end
		begin
			name = sii_page.css('html body center')[1].css('table')[0].css('tr')[0].css('td')[1].css('font').text.strip.titleize
		rescue Exception => e
			name = ''
		end

		if code == 200
			page = Nokogiri::HTML(open("https://portal.sidiv.registrocivil.cl/usuarios-portal/pages/DocumentRequestStatus.xhtml?RUN=#{rut_sii}&type=CEDULA&serial=#{serial}"))
			serial_valid = page.css('.setWidthOfSecondColumn').text == 'Vigente'
		end
		OpenSSL::SSL.const_set(:VERIFY_PEER, OpenSSL::SSL::VERIFY_PEER)
		unless serial_valid
			code = 403
		end
		message = if code == 200
			'Cedula vigente'
		elsif code == 403
			'Documento inválido'
		elsif code == 404
			'Rut inválido'
		end
		respond_to do |format|
			format.json { render json: [rut: rut_sii, name: name, serial: serial, code: code, message: message] }
		end
	end

	def create
		uploaded_io = params[:user][:avatar]
		first_name = params[:user][:first_name]
		last_name = params[:user][:last_name]
		email = params[:user][:email]
		password = params[:user][:password]
		password_confirmation = params[:user][:password_confirmation]
		id_number = params[:user][:id_number]
		invitation_code = params[:user][:invite_code]
		id_document_serial = params[:user][:id_document_serial]

		@user = User.new(avatar: uploaded_io.original_filename, first_name: first_name, last_name: last_name, id_number: id_number, email: email, password: password, password_confirmation: password_confirmation, user_type_id: 3, invite_code: invitation_code, id_document_serial: id_document_serial)
		if @user.save
			#3.times do
			#	@user.invite_codes << InviteCode.create()
			#end
			dir = 'uploads/users/' + @user.id.to_s() + '/'
			avatar_path = dir + uploaded_io.original_filename
			@user.avatar = avatar_path
			@user.save
			FileUtils.mkdir_p('public/' + dir) unless File.directory?(dir)
			File.open(Rails.root.join('public', avatar_path), 'wb') do |file|
				file.write(uploaded_io.read)
			end
			redirect_to user_root_url, :notice => "Registrado!"
		else
			render "new"
		end
	end

	def invite
		emails = params[:e]
		document_id = params[:d]
		invitation_type = params[:t]
		users = []
		emails.split(",").each do |email|
			if invitation_type == 'participant'
				user = User.where('"email" = \'' + email + '\'').first
				unless user
					#Pendiente: Implementar validación diferida según endpoint	
					user = User.new(email: email, password: email, password_confirmation: email)
					pending = UserType.find_by name: 'Pendiente'
					user.user_type = pending
					user.save
				end
				user.reload
				document = Document.find(document_id)
				if document
					if Participant.where('"document_id" = ' + document.id.to_s + ' AND "user_id" = ' + user.id.to_s).exists? == false
						invitee = Role.find_by name: 'Invitado'
						participant = Participant.new(document_id: document.id, role: invitee, user_id: user.id, signed: 'f')
						participant.save
						UserMailer.invitation_email(user, document).deliver
					end
				end
				users << user
			elsif invitation_type == 'free'
				if @invitations_left.count > 0 and !User.exists?(email: email)
					@url = 'http://firmaexpress.com/register?c=' + @invitations_left.first.code
					@code = @invitations_left.first.code
					UserMailer.free_user_invitation_email(@current_user, email, @invitations_left.first).deliver
				end
			end
			respond_to do |format|
				format.json { render :json => [message: "Invitaciones enviadas a " + emails, users: users] }
			end
		end
	end

	def complete_invitee_profile
		user_id = params[:u] #user_id
		user = nil
		if user_id
			user = User.find(user_id)
			@user_email = user.email
		else
			#avatar = params[:avatar]
			first_name = params[:first_name]
			last_name = params[:last_name]
			email = params[:email]
			password = params[:password]
			password_confirmation = params[:password_confirmation]
			id_number = params[:id_number]
			user = User.find_by email: email
			if user
				#user.avatar = avatar
				free = UserType.find_by name: 'Invitado'
				user.user_type = free
				user.first_name = first_name
				user.last_name = last_name
				user.email = email
				user.password = password
				user.id_number = id_number
				user.save
				redirect_to user_root_url
			end
		end
	end

	def complete_invitee_profile_save
#=begin
#=end
	end

	def contact
        name = params[:name]
        email = params[:email]
        message = params[:message]
        UserMailer.contact_email(name, email, message).deliver
        redirect_to root_url
    end

    def update_profile
    	campo = params[:campo]
		valor = params[:valor]
		id = current_user.id
		boolean = []
		user = User.find(id)
		case campo
			when "first_name" 
				user.first_name = valor
			when "last_name"
				user.last_name = valor
			when "email"
				user.email = valor
		end
		save_status = user.save
		respond_to do |format|
			format.json { render :json => [errors: user.errors, save_status: save_status] }
		end
    end

    def profile
    	respond_to do |format|
			format.html
			format.json { render :json => current_user }
		end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/complete_invitee_profile.html.erb
<% content_for :title do %>
- Completar Perfil
<% end %>
<div id="container">
	<div id="headline">
		<h3>Completar Perfil</h3>
	</div>
	<div id="info">
		<%= form_tag(url: users_complete_invitee_profile_path, method: 'post') do %>
			<%= label_tag(:first_name, 'Nombres') %>
			<%= text_field_tag :first_name %>
			<%= label_tag(:last_name, 'Apellidos') %>
			<%= text_field_tag :last_name %>
			<%= label_tag(:id_number, 'RUT') %>
			<%= text_field_tag :id_number %>
			<%= label_tag(:email, 'E-mail') %>
			<%= text_field_tag :email, @user_email, readonly: true %>
			<%= label_tag(:password, 'Contraseña') %>
			<%= password_field_tag :password, autocomplete: "off" %>
			<%= label_tag(:password_confirmation, 'Confirmar contraseña') %>
			<%= password_field_tag :password_confirmation, autocomplete: "off" %>
			<%= submit_tag("Registrarme", { id: 'submit' }) %>
		<% end %>
	</div>
</div>
<%= render "layouts/footer" %>

app/views/users/new.html.erb
<% content_for :title do %>
Login
<% end %>
<div id="container">
	<div id="headline">
		<h3>Registrate con nosotros</h3>
	</div>
	<div id="info">
		<%= form_for @user do |f| %>
			<%= f.label :avatar, 'Imagen de Perfil' %>
		    <%= f.file_field :avatar %>
			<%= f.label :first_name, 'Nombres' %>
			<%= f.text_field :first_name %>
			<%= f.label :last_name, 'Apellidos' %>
			<%= f.text_field :last_name %>
			<%= f.label :id_number, 'RUT' %>
			<%= f.text_field :id_number %>
			<%= f.label :email, 'E-mail' %>
			<%= f.text_field :email %>
			<%= f.label :password, 'Contraseña'%> 
			<%= f.password_field :password %>
			<%= f.label :password_confirmation, 'Confirmar contraseña' %>
			<%= f.password_field :password_confirmation %>
			<%= f.label :invite_code, 'Codigo de invitación' %>
			<%= f.text_field :invite_code %>
			&nbsp;
			<p>Informción importante sobre el registro, derechos, seguridad, etc. Informción importante sobre el registro, derechos, seguridad, etc.Informción importante sobre el registro, derechos, seguridad, etc.Informción importante sobre el registro, derechos, seguridad, etc.Informción importante sobre el registro, derechos, seguridad, etc.Informción importante sobre el registro, derechos, seguridad, etc.Informción importante sobre el registro, derechos, seguridad, etc.Informción importante sobre el registro, derechos, seguridad, etc.Informción importante sobre el registro, derechos, seguridad, etc..</p>
			<%= f.submit "Registrarme", {id: 'submit'} %>
			<% if @user.errors.any? %>
				<div class="error_messages">
				<h2>Form is invalid</h2>
				<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
				</ul>
				</div>
			<% end %>
		<% end %>
		&nbsp;
		<p class="datosextra">*Datos importantes sobre el registro.<br>
		*Datos importantes sobre el registro.<br>
		*Datos importantes sobre el registro.</p>
	</div>
</div>
<%= render "layouts/footer" %>

app/views/users/profile.html.erb
<% content_for :title do %>
	- Perfil
<% end %>
<% content_for :js do %>
<%= javascript_include_tag "angular.min.js" %>
	<script type="text/javascript">
		/* Se inicializa la aplicación y la almacena en app*/
		var app = angular.module("FEFront", []);
		/* Crea el controlador llamado "ProfileController"*/
		app.controller("ProfileController", function($scope, $http){
		/*Llamamos a users controller metodo profile*/		
			$http.get('../profile.json').success(function(data) {
				$scope.user = data;
				console.log(data);
			});

			$scope.updateprofile = function(campo, valor){
				$http.get('../users/update_profile.json?campo='+campo+'&valor='+valor).success(function(data) {
					console.log(data);

				});
			} 
		});

		$(document).on("ready", function () {
			$("img.hiddable").on("click", function () {
			    var id = $(this).parent().attr('id');
			    console.log('#' + id + " .hiddable");
			    $('#' + id + " .hiddable").toggleClass("show");
			});
		});
	</script>
<% end %>
		


<div id="containerdocumentos">
<div id="headline">
<h3>Configuración del Perfil</h3>
</div>
<div id="biblioteca">
<div id="itemactive"><a href="#"><h4>Mis Datos</h4></a></div>
<!--<div id="item"><a href="nuevodocumento.html"><h4>Estadísticas</h4></a></div>
<div id="item"><a href="nuevodocumento.html"><h4>Preguntas Frecuentes</h4></a></div>
<div id="item"><a href="nuevodocumento.html"><h4>Condiciones Legales</h4></a></div>
<div id="item"><a href="nuevodocumento.html"><h4>Seguridad y Privacidad</h4></a></div>-->
</div>
<div id="optionsdocumento"></div>
<div id="perfil" ng-controller="ProfileController">
<div id="perfildatos">
<h5>Datos Personales</h5>
	<img class="img-circle" style="margin-top: -1px; margin-left: 30px" src="<%=root_url + current_user.avatar.to_s %>" width=80 height=80>
	<p><span class="hiddable show" >
	    Rut: {{user.id_number}}
	 </span></p>
	<p id="first_name">
		<span class="hiddable show">
	        Nombre: {{user.first_name}}
	    </span>
	    <span class="hiddable">
	        <input type="text" ng-model="user.first_name"/>
	    </span>    
    </p><br>
    <!--fin-->
    <p id="lastname">
		<span class="hiddable show">
	        Apellido: {{user.last_name}}
	    </span>
	    <span class="hiddable">
	        <input type="text" ng-model="user.last_name"/>
	    </span>
	</p><br>
    <!--fin-->
    <p id="email">
	    <span class="hiddable show">
	        Email: {{user.email}}
	    </span>
	    <span class="hiddable">
	        <input type="text" ng-model="user.email"/>
	    </span>
		<%= image_tag("icono_editar.png", class: "hiddable show", :align=> "right", :alt=>"Modificar") %>
	    <%= image_tag("icono_guardar.png", class: "hiddable", "ng-click" => "updateprofile('email', user.email)", :align=> "right") %> <br>
	</p><br>
	<p id="plan">
		<span>Plan: <%= current_user.subscriber.plans.last.name %></span>
	</p>
	<br>
	<h5>Firma</h5>
	<p>Suba una imagen de su firma.</p>
	<%= form_tag 'users/sign_image', multipart: true do |f| %>
		<%= file_field_tag :sign_image, required: 'required' %>
		<img src="<%= root_url + current_user.sign_image.url %>" height=100 />
		<%= submit_tag "Subir", { id: 'submit' } %>
	<% end %>
	<br>
	<h5>Documentos</h5>
	<p>Máximo: <%= current_user.subscriber.plans.last.documents %></p>
	<p>Nº de Documentos: <%= Participant.where(user: current_user, role_id: 1).count %></p>
	<br>
	<h5>Datos de Usuario</h5>
	<p>Usuario desde: <%= current_user.created_at.to_formatted_s(:db) %></p>
	<br>
</div>
<div id="perfilestadisticas">
<h5>Estadísticas de Actividad</h5>
<p>Datos</p>
</div>
</div>
<div id="importante"><p class="datosextra">Información importante acerca de los usuarios y la legalidad del sistema o seguridad de los datos.</p></div>
</div>
<%= render "layouts/footer" %>