config/routes.rb
FirmaExpressR::Application.routes.draw do
  devise_for :users#, controllers: { registrations:'devise/custom/registrations' }
  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  root 'home#homepage'
  get "home" => "documents#new", as: 'user_root' #"new_document"
  get "show" => "documents#show", :as => "show_document"
  get "documents/new"
  get "sessions/new"
  get "users/new"
  get "users/rut", to: "users#rut"
  get "users/invite", to: "users#invite", as: "invite"
  get "/contact", to: "home#contact", as: "contact_form"
  post "users/contact", to: "users#contact", as: "contact"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "/register" => "users#new", :as => "sign_up"
  get "documents/sign/:id", to: "documents#sign"
  get "documents/destroy/:id", to: "documents#destroy"
  get "participants/:user_id/destroy/:document_id", to: "participants#destroy"
  get "documents/list", to: "documents#list"
  get "check_document/:id", to: "documents#check"
  get "/profile", to: "users#profile", as:"profile"
  get "users/update_profile", to: "users#update_profile", as:"update_profile"
  get "users/complete_invitee_profile", to: "users#complete_invitee_profile"
  post "users/complete_invitee_profile", to: "users#complete_invitee_profile"
  post "users/sign_image", to: "users#sign_image"
  default_url_options :host => "Firmaexpress.dev"
  resources :sessions
  resources :documents
  resources :users
  resources :subscriptions
  get 'paypal/checkout', to: 'subscriptions#paypal_checkout'
  get "/about_us", to: "home#aboutus"
  get "/plans", to: "home#plans"
  get "/benefits", to: "home#benefits"
  get "/terms", to: "home#terms"
  get "/get_plan/:plan_id", to: "home#get_plan"
  post "/get_plan_post", to: "home#get_plan_post"
  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    resources :users, only: [:index, :show] do
      resources :documents, only: [:index, :show] do
        resources :signs, only: [:index, :create]
      end
    end
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :plan
	belongs_to :subscriber
	has_many :invoices
	attr_accessor :paypal_payment_token, :email

	def save_with_payment
		if valid? and payment_provided?
			save_with_paypal_payment
		end
	end

	def save_with_paypal_payment
		response = paypal.make_recurring
		self.paypal_recurring_profile_token = response.profile_id
		save!
	end

	def paypal
		PaypalPayment.new(self)
	end

	def payment_provided?
		paypal_payment_token.present?
	end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
	def new
		@plan = Plan.find(params[:plan_id])
		@subscription = Subscription.new
		@subscription.plan = @plan
		if params[:PayerID]
			@subscription.paypal_customer_token = params[:PayerID]
			@subscription.paypal_payment_token = params[:token]
			@subscription.email = @subscription.paypal.checkout_details.email
		end
	end

	def paypal_checkout
		plan = Plan.find(params[:plan_id])
		subscription = plan.subscriptions.build
		redirect_to subscription.paypal.checkout_url(
			#return_url: new_subscription_url(plan_id: plan.id),
			return_url: new_user_registration_url(plan_id: plan.id),
			cancel_url: root_url)
	end

	def create
		#raise params[:subscription].inspect
		@subscription = Subscription.new(subscription_params)
		if @subscription.save_with_payment
			user = if User.exists? email: @subscription.email
				User.find_by email: @subscription.email
			else
				User.create!(email: @subscription.email, user_type_id: 4, password: '12345678')
			end
			user.subscriber.subscriptions << @subscription
			user.subscriber.save
			#redirect_to @subscription, :notice => "Gracias por subscribirte!"
			redirect_to users_complete_invitee_profile_url(u: user.id)
		else
			render :new
		end
	end

	def show
		@subscription = Subscription.find(params[:id])
	end

	def subscription_params
		params.require(:subscription).permit(:email, :plan_id, :paypal_customer_token, :paypal_payment_token)
	end
end

app/views/subscriptions/new.html.erb
<% content_for :title do %>
- Subscribirse a un plan
<% end %>
<% content_for :style do %>
<% stylesheet_link_tag "master.scss" %>
<% stylesheet_link_tag "http://fonts.googleapis.com/css?family=PT+Sans:400,700" %>
<% stylesheet_link_tag "http://fonts.googleapis.com/css?family=Oswald" %>
<% end %>
<div id="container">
	<div id="headline">
		<h3>Subscripción a plan <%= @plan.name %></h3>
	</div>
	<div id="info">
		<% if @subscription.payment_provided? %>
			<%= form_for @subscription do |f| %>
				<%= f.text_field :email %>
				<%= f.hidden_field :plan_id %>
				<%= f.hidden_field :paypal_customer_token %>
				<%= f.hidden_field :paypal_payment_token %>
				<%= f.submit 'Subscribirse', { id: 'submit' } %>
			<% end %>
			El pago ha sido efectuado
		<% else %>
			<%= link_to image_tag('https://paypal.com/en_US/i/btn/btn_xpressCheckout.gif'), paypal_checkout_path(plan_id: @plan.id) %>
		<% end %>
	</div>
</div>
<%= render "layouts/footer" %>

app/views/subscriptions/show.html.erb
<% content_for :title do %>
- Subscribirse a un plan
<% end %>
<% content_for :style do %>
<% stylesheet_link_tag "master.scss" %>
<% stylesheet_link_tag "http://fonts.googleapis.com/css?family=PT+Sans:400,700" %>
<% stylesheet_link_tag "http://fonts.googleapis.com/css?family=Oswald" %>
<% end %>
<div id="container">
	<div id="headline">
		<h3>Tu subscripción</h3>
	</div>
	<div id="info">
		<p>Te haz sibscrito al plan <strong><%= @subscription.plan.name %></strong> que incluye <strong><%= @subscription.plan.documents %> documentos</strong> por solo <strong><%= number_to_currency @subscription.plan.price_usd %></strong> al mes!</p>
	</div>
</div>
<%= render "layouts/footer" %>