config/routes.rb
FirmaExpressR::Application.routes.draw do
  devise_for :users#, controllers: { registrations:'devise/custom/registrations' }
  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  root 'home#homepage'
  get "home" => "documents#new", as: 'user_root' #"new_document"
  get "show" => "documents#show", :as => "show_document"
  get "documents/new"
  get "sessions/new"
  get "users/new"
  get "users/rut", to: "users#rut"
  get "users/invite", to: "users#invite", as: "invite"
  get "/contact", to: "home#contact", as: "contact_form"
  post "users/contact", to: "users#contact", as: "contact"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "/register" => "users#new", :as => "sign_up"
  get "documents/sign/:id", to: "documents#sign"
  get "documents/destroy/:id", to: "documents#destroy"
  get "participants/:user_id/destroy/:document_id", to: "participants#destroy"
  get "documents/list", to: "documents#list"
  get "check_document/:id", to: "documents#check"
  get "/profile", to: "users#profile", as:"profile"
  get "users/update_profile", to: "users#update_profile", as:"update_profile"
  get "users/complete_invitee_profile", to: "users#complete_invitee_profile"
  post "users/complete_invitee_profile", to: "users#complete_invitee_profile"
  post "users/sign_image", to: "users#sign_image"
  default_url_options :host => "Firmaexpress.dev"
  resources :sessions
  resources :documents
  resources :users
  resources :subscriptions
  get 'paypal/checkout', to: 'subscriptions#paypal_checkout'
  get "/about_us", to: "home#aboutus"
  get "/plans", to: "home#plans"
  get "/benefits", to: "home#benefits"
  get "/terms", to: "home#terms"
  get "/get_plan/:plan_id", to: "home#get_plan"
  post "/get_plan_post", to: "home#get_plan_post"
  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    resources :users, only: [:index, :show] do
      resources :documents, only: [:index, :show] do
        resources :signs, only: [:index, :create]
      end
    end
  end

end

app/views/layouts/_alerts.html.erb
<% flash.each do |name, msg| %>
  <!--<%= content_tag :div, msg, :id => "flash_#{name}" %>-->
<% end %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
	<p class="left">Derechos Reservados a <strong>Firma Express 2014</strong> / <a href="terms">Términos y Condiciones</a> / <a href="preguntasfrecuentes.html">Preguntas Frecuentes</a> / <strong>Mail:</strong> contacto@firmaexpress.cl</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="FEFront">
<head>
  <title>Firma Express <%= yield :title %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => false %>
  <%= stylesheet_link_tag "joyride-2.1.css"%>
  <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Yellowtail|Kaushan+Script|Damion' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Bree+Serif' rel='stylesheet' type='text/css'>
  <%= yield :styles %>
  <% #javascript_include_tag "application", "data-turbolinks-track" => false %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <%= javascript_include_tag "angular.min.js" %>
  <%= javascript_include_tag "angular-re-captcha.js" %>
  <% if Rails.env.production? %>
  <%= javascript_include_tag "ga.js" %>
  <%= javascript_include_tag "zopim.js" %>
  <% end %>
  <%= javascript_include_tag "skrollr.js" %>
  <%= javascript_include_tag "jquery-1.10.1.js" %>
  <%= javascript_include_tag "jquery.cookie.js" %>
  <%= javascript_include_tag "modernizr.mq.js" %>
  <%= javascript_include_tag "jquery.joyride-2.1.js" %>
  <%= csrf_meta_tags %>
  <%= yield :js %>
</head>
<body>
	<header>
		<div id="logo">
      <% if current_user %>
        <a href="<%= user_root_url %>">
      <% else %>
			 <a href="<%= root_url %>">
      <% end %>
        <%= image_tag "FirmaExpress1.png", { height: 60, width: 321 } %>
      </a>
		</div>
    <div id="wrap">
        <nav>
            <ul>
              <% if current_user %>
                <% if current_user.subscriber.plans.last.name == 'Gratis' %>
                  <li class="cambiaAplan"><%= link_to 'Obtener un plan', plans_path %></li>
                <% end %>
                <li><%= link_to "Bienvenido #{current_user.first_name}", profile_path %></li>
                <li><img class="img-circle" style="margin-top: -5px; margin-left: 5px" src="<%= root_url + current_user.avatar.to_s %>" width=30 height=30></li>
                <% if current_user.user_type_id == 1 %>
                <% end %>
                <li><%= link_to 'Home', user_root_path %></li>
                <li><%= link_to("Logout", destroy_user_session_path, :method => :delete) %></li>
              <% else %>
                <li><%= link_to 'Iniciar Sesión', new_user_session_path %></li>
                <li><%= link_to 'Nosotros', about_us_path %></li>
                <!--<li><%= link_to 'Planes', plans_path %></li>-->
                <li><%= link_to 'Beneficios', benefits_path %></li>
                <li><%= link_to 'Preguntas frecuentes', contact_form_path %></li>
                <li><%= link_to 'Contacto', contact_form_path %></li>
              <% end %>
            </ul>
        </nav>
      </div>
	</header>

<%= yield %>

</body>
</html>